
; MIKROISLEMCILER PROJE ODEV - AKILLI EV SISTEMI - Board 1 -
	
;***************************************
 
;Mervenur Çakmakoðlu  152120221128
;Selin Öztürk 151220222053

;***************************************

	LIST P=16F877A
	#INCLUDE <P16F877A.INC>

	
	__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

	
	CBLOCK 0x70
	    W_YEDEK
	    STATUS_YEDEK
	ENDC

	
	CBLOCK 0x20
	    
	    HAN_GECICI      
	    GIRIS_ONLAR
	    GIRIS_BIRLER
	    GIRIS_ONDA
	    GIRIS_ADIM      
	    HAN_SAYACI      
	    HAN1, HAN2, HAN3, HAN4
	    EKRAN_DURUMU    

	    
	    OLCULEN_TAM
	    OLCULEN_ONDA
	    ISTENEN_TAM
	    ISTENEN_ONDA
	    FAN_HIZI

	    
	    TUS_DEGERI
	    TUS_BASILDI_FLG
	    AYAR_MODU       
	    GECIKME1, GECIKME2

	    
	    SAYAC_GENEL
	    TOPLAM_L
	    TOPLAM_H
	    KAYDIRMA_SAY
	    ADC_SURE_SAY
	    ESKI_ADC_DEGER

	    
	    GELEN_VERI
	    GIDEN_VERI
	    SANIYE_SAYAC    
	    EKRAN_SURE      
	    W_EKRAN_TEMP
	ENDC

    
	ORG 0x0000
	GOTO BASLA

    
	ORG 0x0004
    KESME_SERV?S?:
	MOVWF   W_YEDEK
	SWAPF   STATUS, W
	MOVWF   STATUS_YEDEK
	BCF     STATUS, RP0
	BCF     STATUS, RP1

	
	BTFSS   PIR1, TMR1IF
	GOTO    KESME_CIKIS

	BCF     PIR1, TMR1IF        

	
	MOVLW   0xFD
	MOVWF   TMR1H
	MOVLW   0x8F
	MOVWF   TMR1L

	CALL    EKRAN_YENILE        

	
	INCF    SANIYE_SAYAC, F
	MOVLW   d'200'              
	SUBWF   SANIYE_SAYAC, W
	BTFSS   STATUS, C
	GOTO    KESME_CIKIS         

	
	CLRF    SANIYE_SAYAC

	
	MOVF    TMR0, W
	MOVWF   FAN_HIZI
	CLRF    TMR0                

	
	INCF    EKRAN_SURE, F
	BTFSS   EKRAN_SURE, 0       
	GOTO    KESME_CIKIS

	INCF    EKRAN_DURUMU, F
	MOVF    EKRAN_DURUMU, W
	XORLW   d'3'                
	BTFSC   STATUS, Z
	CLRF    EKRAN_DURUMU

    KESME_CIKIS:
	SWAPF   STATUS_YEDEK, W
	MOVWF   STATUS
	SWAPF   W_YEDEK, F
	SWAPF   W_YEDEK, W
	RETFIE

    
	ORG 0x0200
    TABLO_7SEG:
	ANDLW   0x0F
	ADDWF   PCL, F
	RETLW   b'00111111' ; 0
	RETLW   b'00000110' ; 1
	RETLW   b'01011011' ; 2
	RETLW   b'01001111' ; 3
	RETLW   b'01100110' ; 4
	RETLW   b'01101101' ; 5
	RETLW   b'01111101' ; 6
	RETLW   b'00000111' ; 7
	RETLW   b'01111111' ; 8
	RETLW   b'01101111' ; 9
	RETLW   b'00111001' ; C
	RETLW   b'01011110' ; d
	RETLW   b'01110001' ; F
	RETLW   b'00000000' ; Bos
	RETLW   b'01000000' ; -
	RETLW   b'01111001' ; E

    
	ORG 0x0300
    BASLA:
	
	BANKSEL ADCON1
	MOVLW   b'10001110'         
	MOVWF   ADCON1

	BANKSEL TRISD
	CLRF    TRISD
	CLRF    TRISE

	BANKSEL TRISA
	CLRF    TRISA
	BSF     TRISA, 0            
	BSF     TRISA, 4            
	BCF     TRISA, 5

	BANKSEL TRISC
	BCF     TRISC, 0            
	BCF     TRISC, 1
	BSF     TRISC, 7            
	BCF     TRISC, 6            

	BANKSEL TRISB
	MOVLW   b'11110000'         
	MOVWF   TRISB

	
	BANKSEL SPBRG
	MOVLW   d'25'
	MOVWF   SPBRG
	MOVLW   b'00100100'         
	MOVWF   TXSTA

	
	BANKSEL OPTION_REG
	MOVLW   b'00101000'         
	MOVWF   OPTION_REG

	
	BANKSEL PIE1
	BSF     PIE1, TMR1IE        

	
	BANKSEL RCSTA
	MOVLW   b'10010000'         
	MOVWF   RCSTA

	
	BANKSEL T1CON
	MOVLW   b'00110001'         
	MOVWF   T1CON

	BANKSEL CMCON
	MOVLW   0x07
	MOVWF   CMCON

	BANKSEL ADCON0
	MOVLW   b'10000001'         
	MOVWF   ADCON0

	BANKSEL INTCON
	BSF     INTCON, GIE         
	BSF     INTCON, PEIE        

	
	BANKSEL PORTD
	CLRF    PORTD
	CLRF    PORTE
	CLRF    PORTA

	CLRF    HAN_SAYACI
	MOVLW   d'25'               
	MOVWF   ISTENEN_TAM
	CLRF    ISTENEN_ONDA

	CLRF    AYAR_MODU
	CLRF    EKRAN_DURUMU
	CLRF    SANIYE_SAYAC
	CLRF    FAN_HIZI
	CLRF    TMR0
	CLRF    ESKI_ADC_DEGER

	MOVLW   d'50'
	MOVWF   ADC_SURE_SAY
	CLRF    TOPLAM_L
	CLRF    TOPLAM_H

	CALL    ADC_OKU
	CALL    ISI_KONTROL_MANTIGI

    
    
    
    ANA_DONGU:
	
	MOVF    AYAR_MODU, F
	BTFSS   STATUS, Z
	GOTO    AYAR_EKRANI_GOSTER

	
	DECFSZ  ADC_SURE_SAY, F
	GOTO    SICAKLIK_ISLEM_ATLA

	MOVLW   d'50'               
	MOVWF   ADC_SURE_SAY
	CALL    ADC_OKU
	CALL    ISI_KONTROL_MANTIGI

    SICAKLIK_ISLEM_ATLA:
	
	MOVF    EKRAN_DURUMU, W
	XORLW   0
	BTFSC   STATUS, Z
	CALL    HAZIRLA_ORTAM_SICAKLIK

	MOVF    EKRAN_DURUMU, W
	XORLW   1
	BTFSC   STATUS, Z
	CALL    HAZIRLA_ISTENEN_SICAKLIK

	MOVF    EKRAN_DURUMU, W
	XORLW   2
	BTFSC   STATUS, Z
	CALL    HAZIRLA_FAN_HIZI

	
	GOTO    TUS_KONTROL_NOKTASI

    AYAR_EKRANI_GOSTER:
	
	MOVF    GIRIS_ONLAR, W
	MOVWF   HAN1
	MOVF    GIRIS_BIRLER, W
	MOVWF   HAN2
	MOVF    GIRIS_ONDA, W
	MOVWF   HAN3
	MOVLW   d'11'               
	MOVWF   HAN4

    TUS_KONTROL_NOKTASI:
	CALL    KLAVYE_TARAMA
	MOVF    TUS_BASILDI_FLG, F
	BTFSS   STATUS, Z
	CALL    TUS_ISLE
	CLRF    TUS_BASILDI_FLG

	
	CALL    HABERLESME_KONTROL

	CALL    GECIKME_MS
	GOTO    ANA_DONGU

    
    ; SERI HABERLESME (PC KOMUTLARI)
    
    HABERLESME_KONTROL:
    BANKSEL PIR1
    BTFSS   PIR1, RCIF          
    RETURN                      

    BANKSEL RCREG
    MOVF    RCREG, W
    MOVWF   GELEN_VERI          
    BANKSEL PORTA

    
    
    MOVF    GELEN_VERI, W
    XORLW   0x01
    BTFSC   STATUS, Z
    GOTO    GONDER_ISTENEN_ONDA

    
    MOVF    GELEN_VERI, W
    XORLW   0x02
    BTFSC   STATUS, Z
    GOTO    GONDER_ISTENEN_TAM

    
    MOVF    GELEN_VERI, W
    XORLW   0x03
    BTFSC   STATUS, Z
    GOTO    GONDER_ORTAM_ONDA

    
    MOVF    GELEN_VERI, W
    XORLW   0x04
    BTFSC   STATUS, Z
    GOTO    GONDER_ORTAM_TAM

    
    MOVF    GELEN_VERI, W
    XORLW   0x05
    BTFSC   STATUS, Z
    GOTO    GONDER_FAN_HIZI

    
    MOVF    GELEN_VERI, W
    XORLW   0x06
    BTFSC   STATUS, Z
    GOTO    GONDER_ISTENEN_TAM      

    
    MOVF    GELEN_VERI, W
    ANDLW   b'11000000'
    XORLW   b'10000000'
    BTFSC   STATUS, Z
    GOTO    AYARLA_ISTENEN_ONDA

    
    MOVF    GELEN_VERI, W
    ANDLW   b'11000000'
    XORLW   b'11000000'
    BTFSC   STATUS, Z
    GOTO    AYARLA_ISTENEN_TAM

    RETURN

    
    GONDER_ISTENEN_ONDA:
	MOVF    ISTENEN_ONDA, W
	GOTO    UART_YOLLA
    GONDER_ISTENEN_TAM:
	MOVF    ISTENEN_TAM, W
	GOTO    UART_YOLLA
    GONDER_ORTAM_ONDA:
	MOVF    OLCULEN_ONDA, W
	GOTO    UART_YOLLA
    GONDER_ORTAM_TAM:
	MOVF    OLCULEN_TAM, W
	GOTO    UART_YOLLA
    GONDER_FAN_HIZI:
	MOVF    FAN_HIZI, W
	GOTO    UART_YOLLA

    UART_YOLLA:
	MOVWF   GIDEN_VERI
	BANKSEL TXREG
	MOVWF   TXREG
	BANKSEL PIR1
    BEKLE_TX:
	BTFSS   PIR1, TXIF      
	GOTO    BEKLE_TX
	BANKSEL PORTA
	RETURN

    ;  Ayarlama Islemleri
    AYARLA_ISTENEN_ONDA:
	MOVF    GELEN_VERI, W
	ANDLW   b'00111111'     
	MOVWF   ISTENEN_ONDA
	CALL    ISI_KONTROL_MANTIGI
	RETURN
    AYARLA_ISTENEN_TAM:
	MOVF    GELEN_VERI, W
	ANDLW   b'00111111'
	MOVWF   ISTENEN_TAM
	CALL    ISI_KONTROL_MANTIGI
	RETURN

   
    ; EKRAN ICIN SAYILAR
    
    HAZIRLA_ORTAM_SICAKLIK:
	CLRF    HAN1
	MOVF    OLCULEN_TAM, W
	MOVWF   HAN_GECICI
	CALL    BASAMAKLARI_AYIR
	MOVF    OLCULEN_ONDA, W
	MOVWF   HAN3
	MOVLW   d'10'           
	MOVWF   HAN4
	RETURN

    HAZIRLA_ISTENEN_SICAKLIK:
	CLRF    HAN1
	MOVF    ISTENEN_TAM, W
	MOVWF   HAN_GECICI
	CALL    BASAMAKLARI_AYIR
	MOVF    ISTENEN_ONDA, W
	MOVWF   HAN3
	MOVLW   d'11'           
	MOVWF   HAN4
	RETURN

    HAZIRLA_FAN_HIZI:
	CLRF    HAN1
	MOVF    FAN_HIZI, W
	MOVWF   HAN_GECICI
	CALL    BASAMAKLARI_AYIR
	CLRF    HAN3
	MOVLW   d'12'           
	MOVWF   HAN4
	RETURN

    BASAMAKLARI_AYIR:
    BOL_ONLAR:
	MOVLW   d'10'
	SUBWF   HAN_GECICI, W
	BTFSS   STATUS, C
	GOTO    BOLME_BITTI
	MOVWF   HAN_GECICI
	INCF    HAN1, F
	GOTO    BOL_ONLAR
    BOLME_BITTI:
	MOVF    HAN_GECICI, W
	MOVWF   HAN2
	RETURN

    
    ; EKRAN TARAMASI 
    
    EKRAN_YENILE:
	CLRF    PORTE               
	BCF     PORTA, 5
	MOVLW   HIGH TABLO_7SEG
	MOVWF   PCLATH

	MOVF    HAN_SAYACI, W
	ANDLW   0x03
	MOVWF   W_EKRAN_TEMP

	MOVF    W_EKRAN_TEMP, W
	BTFSC   STATUS, Z
	GOTO    HAN1_YAK
	MOVF    W_EKRAN_TEMP, W
	XORLW   1
	BTFSC   STATUS, Z
	GOTO    HAN2_YAK
	MOVF    W_EKRAN_TEMP, W
	XORLW   2
	BTFSC   STATUS, Z
	GOTO    HAN3_YAK
	GOTO    HAN4_YAK

    HAN1_YAK:
	MOVF    HAN1, W
	CALL    TABLO_7SEG
	MOVWF   PORTD
	MOVLW   b'00000001'
	MOVWF   PORTE
	GOTO    SONRAKI_HANE
    HAN2_YAK:
	MOVF    HAN2, W
	CALL    TABLO_7SEG
	IORLW   b'10000000'     
	MOVWF   PORTD
	MOVLW   b'00000010'
	MOVWF   PORTE
	GOTO    SONRAKI_HANE
    HAN3_YAK:
	MOVF    HAN3, W
	CALL    TABLO_7SEG
	MOVWF   PORTD
	MOVLW   b'00000100'
	MOVWF   PORTE
	GOTO    SONRAKI_HANE
    HAN4_YAK:
	MOVF    HAN4, W
	CALL    TABLO_7SEG
	MOVWF   PORTD
	BSF     PORTA, 5
	GOTO    SONRAKI_HANE
    SONRAKI_HANE:
	INCF    HAN_SAYACI, F
	CLRF    PCLATH
	RETURN

    
    ; ADC OKUMA + ORTALAMA ALMA
    
    ADC_OKU:
	CLRF    TOPLAM_L
	CLRF    TOPLAM_H
	MOVLW   d'32'           
	MOVWF   SAYAC_GENEL
    ADC_DONGUSU:
	BANKSEL ADCON0
	BSF     ADCON0, GO
    BEKLE_ADC:
	BTFSC   ADCON0, GO
	GOTO    BEKLE_ADC

	BANKSEL ADRESL
	MOVF    ADRESL, W
	BANKSEL TOPLAM_L
	ADDWF   TOPLAM_L, F
	BTFSC   STATUS, C
	INCF    TOPLAM_H, F
	DECFSZ  SAYAC_GENEL, F
	GOTO    ADC_DONGUSU

	
	MOVLW   d'5'
	MOVWF   KAYDIRMA_SAY
    KAYDIR_BOL:
	BCF     STATUS, C
	RRF     TOPLAM_H, F
	RRF     TOPLAM_L, F
	DECFSZ  KAYDIRMA_SAY, F
	GOTO    KAYDIR_BOL

	
	MOVF    TOPLAM_L, W
	SUBWF   ESKI_ADC_DEGER, W
	BTFSC   STATUS, Z
	GOTO    DEGISIM_YOK
	MOVF    ESKI_ADC_DEGER, W
	ADDLW   d'1'
	XORWF   TOPLAM_L, W
	BTFSC   STATUS, Z
	GOTO    DEGISIM_YOK
	MOVF    ESKI_ADC_DEGER, W
	ADDLW   d'255'
	XORWF   TOPLAM_L, W
	BTFSC   STATUS, Z
	GOTO    DEGISIM_YOK

	MOVF    TOPLAM_L, W
	MOVWF   ESKI_ADC_DEGER
	GOTO    DEGERI_HESAPLA
    DEGISIM_YOK:
	MOVF    ESKI_ADC_DEGER, W
	MOVWF   TOPLAM_L
    DEGERI_HESAPLA:
	
	MOVF    TOPLAM_L, W
	BANKSEL OLCULEN_TAM
	MOVWF   OLCULEN_TAM
	MOVLW   d'1'
	SUBWF   OLCULEN_TAM, F
	BCF     STATUS, C
	RRF     OLCULEN_TAM, F
	BTFSC   STATUS, C
	GOTO    BUCUK_VAR
	CLRF    OLCULEN_ONDA
	RETURN
    BUCUK_VAR:
	MOVLW   d'5'
	MOVWF   OLCULEN_ONDA
	RETURN

    ISI_KONTROL_MANTIGI:
	BANKSEL PORTC
	MOVF    ISTENEN_TAM, W
	SUBWF   OLCULEN_TAM, W
	BTFSS   STATUS, Z
	GOTO    TAM_KISIM_FARK
	MOVF    ISTENEN_ONDA, W
	SUBWF   OLCULEN_ONDA, W
	BTFSC   STATUS, C
	GOTO    SOGUTMA_AKTIF
	GOTO    ISITMA_AKTIF
    TAM_KISIM_FARK:
	BTFSC   STATUS, C
	GOTO    SOGUTMA_AKTIF
	GOTO    ISITMA_AKTIF
    SOGUTMA_AKTIF:
	BCF     PORTC, 0        ; Isitici Kapat
	BSF     PORTC, 1        ; Sogutucu Ac
	RETURN
    ISITMA_AKTIF:
	BSF     PORTC, 0        ; Isitici Ac
	BCF     PORTC, 1        ; Sogutucu Kapat
	RETURN

    
    ; Keypad Okuma
    
    KLAVYE_TARAMA:
	CLRF    TUS_BASILDI_FLG
	BANKSEL PORTB

	; 1. SUTUN
	MOVLW   b'11111110'
	MOVWF   PORTB
	CALL    GECIKME_AZ
	BTFSS   PORTB, 4
	GOTO    KONTROL_1
	BTFSS   PORTB, 5
	GOTO    KONTROL_2
	BTFSS   PORTB, 6
	GOTO    KONTROL_3
	BTFSS   PORTB, 7
	GOTO    KONTROL_A

	; 2. SUTUN
	MOVLW   b'11111101'
	MOVWF   PORTB
	CALL    GECIKME_AZ
	BTFSS   PORTB, 4
	GOTO    KONTROL_4
	BTFSS   PORTB, 5
	GOTO    KONTROL_5
	BTFSS   PORTB, 6
	GOTO    KONTROL_6
	BTFSS   PORTB, 7
	GOTO    KONTROL_B

	; 3. SUTUN
	MOVLW   b'11111011'
	MOVWF   PORTB
	CALL    GECIKME_AZ
	BTFSS   PORTB, 4
	GOTO    KONTROL_7
	BTFSS   PORTB, 5
	GOTO    KONTROL_8
	BTFSS   PORTB, 6
	GOTO    KONTROL_9
	BTFSS   PORTB, 7
	GOTO    KONTROL_C

	; 4. SUTUN
	MOVLW   b'11110111'
	MOVWF   PORTB
	CALL    GECIKME_AZ
	BTFSS   PORTB, 4
	GOTO    KONTROL_YILDIZ
	BTFSS   PORTB, 5
	GOTO    KONTROL_0
	BTFSS   PORTB, 6
	GOTO    KONTROL_KARE
	BTFSS   PORTB, 7
	GOTO    KONTROL_D
	RETURN

    ; Tus tanimlamalari
    KONTROL_1: CALL ARK_SONDURME
	       BTFSC PORTB, 4
	       RETURN
	       MOVLW d'1'
	       GOTO TUS_BULUNDU
    KONTROL_2: CALL ARK_SONDURME
	       BTFSC PORTB, 5
	       RETURN
	       MOVLW d'2'
	       GOTO TUS_BULUNDU
    KONTROL_3: CALL ARK_SONDURME
	       BTFSC PORTB, 6
	       RETURN
	       MOVLW d'3'
	       GOTO TUS_BULUNDU
    KONTROL_A: CALL ARK_SONDURME
	       BTFSC PORTB, 7
	       RETURN
	       MOVLW 0x0A
	       GOTO TUS_BULUNDU
    KONTROL_4: CALL ARK_SONDURME
	       BTFSC PORTB, 4
	       RETURN
	       MOVLW d'4'
	       GOTO TUS_BULUNDU
    KONTROL_5: CALL ARK_SONDURME
	       BTFSC PORTB, 5
	       RETURN
	       MOVLW d'5'
	       GOTO TUS_BULUNDU
    KONTROL_6: CALL ARK_SONDURME
	       BTFSC PORTB, 6
	       RETURN
	       MOVLW d'6'
	       GOTO TUS_BULUNDU
    KONTROL_B: CALL ARK_SONDURME
	       BTFSC PORTB, 7
	       RETURN
	       MOVLW 0x0B
	       GOTO TUS_BULUNDU
    KONTROL_7: CALL ARK_SONDURME
	       BTFSC PORTB, 4
	       RETURN
	       MOVLW d'7'
	       GOTO TUS_BULUNDU
    KONTROL_8: CALL ARK_SONDURME
	       BTFSC PORTB, 5
	       RETURN
	       MOVLW d'8'
	       GOTO TUS_BULUNDU
    KONTROL_9: CALL ARK_SONDURME
	       BTFSC PORTB, 6
	       RETURN
	       MOVLW d'9'
	       GOTO TUS_BULUNDU
    KONTROL_C: CALL ARK_SONDURME
	       BTFSC PORTB, 7
	       RETURN
	       MOVLW 0x0C
	       GOTO TUS_BULUNDU
    KONTROL_YILDIZ: CALL ARK_SONDURME
	       BTFSC PORTB, 4
	       RETURN
	       MOVLW 0x0E       
	       GOTO TUS_BULUNDU
    KONTROL_0: CALL ARK_SONDURME
	       BTFSC PORTB, 5
	       RETURN
	       MOVLW d'0'
	       GOTO TUS_BULUNDU
    KONTROL_KARE: CALL ARK_SONDURME
	       BTFSC PORTB, 6
	       RETURN
	       MOVLW 0x0F       
	       GOTO TUS_BULUNDU
    KONTROL_D: CALL ARK_SONDURME
	       BTFSC PORTB, 7
	       RETURN
	       MOVLW 0x0D
	       GOTO TUS_BULUNDU

    TUS_BULUNDU:
	MOVWF   TUS_DEGERI
	MOVLW   1
	MOVWF   TUS_BASILDI_FLG

	
    BEKLE_BIRAK:
	MOVLW   b'11110000'      
	MOVWF   PORTB
	NOP
	MOVF    PORTB, W
	ANDLW   0xF0             
	XORLW   0xF0             
	BTFSS   STATUS, Z        
	GOTO    BEKLE_BIRAK

	CALL    ARK_SONDURME
	RETURN

    
    ; Tuslar
    
    TUS_ISLE:
	; A tusu ayar modunu acar
	MOVF    TUS_DEGERI, W
	XORLW   0x0A
	BTFSC   STATUS, Z
	GOTO    AYAR_BASLAT

	; Ayar modu aktif degilse diger tuslara bakma
	MOVF    AYAR_MODU, F
	BTFSC   STATUS, Z
	RETURN

	; Kare tusu onayla ve cik
	MOVF    TUS_DEGERI, W
	XORLW   0x0F
	BTFSC   STATUS, Z
	GOTO    AYAR_ONAYLA

	; Yildiz tusu virgul
	MOVF    TUS_DEGERI, W
	XORLW   0x0E
	BTFSC   STATUS, Z
	GOTO    VIRGULE_GEC

	; Sayi mi? (0-9)
	MOVF    TUS_DEGERI, W
	SUBLW   d'9'
	BTFSS   STATUS, C
	RETURN

	; Hangi basamaktayiz?
	MOVF    GIRIS_ADIM, W
	XORLW   0
	BTFSC   STATUS, Z
	GOTO    ONLAR_KAYDET
	MOVF    GIRIS_ADIM, W
	XORLW   1
	BTFSC   STATUS, Z
	GOTO    BIRLER_KAYDET
	MOVF    GIRIS_ADIM, W
	XORLW   3
	BTFSC   STATUS, Z
	GOTO    ONDA_KAYDET
	RETURN

    AYAR_BASLAT:
	MOVLW   1
	MOVWF   AYAR_MODU
	CLRF    GIRIS_ADIM
	CLRF    GIRIS_ONLAR
	CLRF    GIRIS_BIRLER
	CLRF    GIRIS_ONDA
	RETURN

    AYAR_ONAYLA:
	
	CLRF    W_EKRAN_TEMP
	 
	MOVF    GIRIS_ONLAR, F
	BTFSC   STATUS, Z
	GOTO    BIRLERI_EKLE
	 
	MOVF    GIRIS_ONLAR, W
	MOVWF   SAYAC_GENEL
    CARP_10:
	MOVLW   d'10'
	ADDWF   W_EKRAN_TEMP, F
	DECFSZ  SAYAC_GENEL, F
	GOTO    CARP_10

    BIRLERI_EKLE:
	MOVF    GIRIS_BIRLER, W
	ADDWF   W_EKRAN_TEMP, F 

	; Limit Kontrolleri
	
	MOVLW   d'10'
	SUBWF   W_EKRAN_TEMP, W
	BTFSS   STATUS, C
	GOTO    AYAR_IPTAL

	
	MOVF    W_EKRAN_TEMP, W
	SUBLW   d'50'
	BTFSS   STATUS, C
	GOTO    AYAR_IPTAL

	; Degerleri kaydet
	MOVF    W_EKRAN_TEMP, W
	MOVWF   ISTENEN_TAM 
	 
	MOVF    GIRIS_ONDA, W
	MOVWF   ISTENEN_ONDA
	 
	CLRF    AYAR_MODU
	GOTO    AYAR_BITTI

    AYAR_IPTAL:
	CLRF    AYAR_MODU
	RETURN

    AYAR_BITTI:
	CLRF    EKRAN_DURUMU
	CALL    ISI_KONTROL_MANTIGI
	RETURN

    VIRGULE_GEC:
	MOVLW   3
	MOVWF   GIRIS_ADIM
	RETURN

    ONLAR_KAYDET:
	MOVF    TUS_DEGERI, W
	MOVWF   GIRIS_ONLAR
	MOVLW   1
	MOVWF   GIRIS_ADIM
	RETURN

    BIRLER_KAYDET:
	MOVF    TUS_DEGERI, W
	MOVWF   GIRIS_BIRLER
	MOVLW   2
	MOVWF   GIRIS_ADIM
	RETURN

    ONDA_KAYDET:
	MOVF    TUS_DEGERI, W
	MOVWF   GIRIS_ONDA
	MOVLW   4
	MOVWF   GIRIS_ADIM
	RETURN


; Gecikmeler

GECIKME_AZ:
	MOVLW   d'5'
	MOVWF   GECIKME1
	GOTO    DONGU_1
ARK_SONDURME:
	MOVLW   d'40'
	MOVWF   GECIKME1
DONGU_1:
	MOVLW   d'200'
	MOVWF   GECIKME2
DONGU_2:
	DECFSZ  GECIKME2, F
	GOTO    DONGU_2
	DECFSZ  GECIKME1, F
	GOTO    DONGU_1
	RETURN

GECIKME_MS:
	MOVLW   d'10'
	MOVWF   GECIKME1
D1:
	MOVLW   d'50'
	MOVWF   GECIKME2
D2:
	DECFSZ  GECIKME2, F
	GOTO    D2
	DECFSZ  GECIKME1, F
	GOTO    D1
	RETURN
	 
	END